# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zymurgy}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mike Breeze"]
  s.date = %q{2010-12-07}
  s.description = %q{(n) The branch of chemistry that deals with fermentation processes, as in brewing.

Zymurgy is a collection of libraries to help with beer brewing calculations:
        * Gravity points
        * Hop utilisation
        * Boil times and volumes}
  s.email = %q{breezy@binningup.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/zymurgy.rb",
     "lib/zymurgy/acts_as_brew_recipe.rb",
     "lib/zymurgy/acts_as_brewery.rb",
     "lib/zymurgy/acts_as_fermentable.rb",
     "lib/zymurgy/utils.rb",
     "spec/acts_as_brew_recipe_spec.rb",
     "spec/acts_as_brewery_spec.rb",
     "spec/acts_as_fermentable_spec.rb",
     "spec/database.yml",
     "spec/patches/float.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "spec/zymurgy_utils_spec.rb",
     "zymurgy.gemspec"
  ]
  s.homepage = %q{http://github.com/breezy/zymurgy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A beer brewing gem}
  s.test_files = [
    "spec/acts_as_brew_recipe_spec.rb",
     "spec/acts_as_brewery_spec.rb",
     "spec/acts_as_fermentable_spec.rb",
     "spec/acts_as_hop_addition_spec.rb",
     "spec/patches/float.rb",
     "spec/schema.rb",
     "spec/spec_helper.rb",
     "spec/zymurgy_utils_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.8"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.8"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.8"])
  end
end

